import { Star, TrendingUp, Users, DollarSign, Award, CheckCircle2, Play, Quote } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const ResultsProof = () => {
  const testimonials = [
    {
      name: "Sarah Chen",
      role: "SaaS Founder",
      image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
      result: "$47K in 90 Days",
      before: "200 followers, 0 clients",
      after: "12K followers, 8 clients/month",
      quote: "I was skeptical about LinkedIn. Three months in, I've closed more deals than the entire previous year on other platforms. The operator secrets are legit.",
      metrics: {
        revenue: "+$47,000",
        followers: "+11,800",
        engagement: "430%"
      }
    },
    {
      name: "Marcus Thompson",
      role: "B2B Consultant",
      image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus",
      result: "$120K First Year",
      before: "Cold outreach fatigue",
      after: "Inbound lead machine",
      quote: "Stopped cold messaging. Started posting strategically. Now clients reach out to ME. This completely transformed my business model.",
      metrics: {
        revenue: "+$120,000",
        followers: "+23,400",
        engagement: "580%"
      }
    },
    {
      name: "Jessica Rodriguez",
      role: "Executive Coach",
      image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica",
      result: "$85K in 6 Months",
      before: "3K followers, inconsistent income",
      after: "45K followers, waitlist of clients",
      quote: "I thought I needed 100K followers to monetize. Wrong. The LinkedIn Operator method showed me how to convert with precision, not just post for likes.",
      metrics: {
        revenue: "+$85,000",
        followers: "+42,000",
        engagement: "720%"
      }
    }
  ];

  const caseStudies = [
    {
      industry: "Tech Consulting",
      timeline: "60 Days",
      startFollowers: "450",
      endFollowers: "8.2K",
      revenue: "$32K",
      highlight: "First viral post hit 340K views"
    },
    {
      industry: "Financial Services",
      timeline: "90 Days",
      startFollowers: "1.2K",
      endFollowers: "18.5K",
      revenue: "$67K",
      highlight: "Client acquisition cost dropped 73%"
    },
    {
      industry: "Marketing Agency",
      timeline: "120 Days",
      startFollowers: "2.8K",
      endFollowers: "34K",
      revenue: "$156K",
      highlight: "Built 6-figure recurring revenue"
    }
  ];

  const stats = [
    { label: "Average Revenue Increase", value: "$78K", subtext: "First 6 months", icon: DollarSign },
    { label: "Client Success Rate", value: "94%", subtext: "Hit revenue goals", icon: TrendingUp },
    { label: "Creators Scaled", value: "200+", subtext: "Across 40+ industries", icon: Users },
    { label: "Combined Revenue", value: "$12M+", subtext: "Generated by students", icon: Award }
  ];

  return (
    <section className="py-32 bg-gradient-to-b from-background via-background to-primary/5">
      <div className="container mx-auto px-4 max-w-7xl">
        
        {/* Header */}
        <div className="text-center mb-20">
          <Badge className="mb-4 px-6 py-2 text-sm">VERIFIED RESULTS</Badge>
          <h2 className="text-6xl font-bold mb-6">
            Real Operators. <span className="text-gradient">Real Results.</span>
          </h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            These aren't fake screenshots or cherry-picked wins. These are actual creators who followed the LinkedIn Operator playbook and transformed their business.
          </p>
        </div>

        {/* Stats Grid */}
        <div className="grid md:grid-cols-4 gap-6 mb-32">
          {stats.map((stat, index) => (
            <Card key={index} className="border-primary/20 bg-gradient-to-br from-card to-primary/5 hover:shadow-lg transition-all duration-300 hover:scale-105">
              <CardContent className="p-8 text-center">
                <stat.icon className="w-10 h-10 text-primary mx-auto mb-4" />
                <div className="text-4xl font-bold text-gradient mb-2">{stat.value}</div>
                <div className="text-sm font-semibold text-foreground mb-1">{stat.label}</div>
                <div className="text-xs text-muted-foreground">{stat.subtext}</div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Featured Testimonials */}
        <div className="mb-32">
          <div className="text-center mb-16">
            <h3 className="text-4xl font-bold mb-4">
              From <span className="text-destructive">Struggling</span> to <span className="text-primary">Scaling</span>
            </h3>
            <p className="text-lg text-muted-foreground">Real transformations from real operators</p>
          </div>

          <div className="grid lg:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <Card key={index} className="border-2 border-primary/20 hover:border-primary/40 transition-all duration-300 bg-gradient-to-br from-card to-background overflow-hidden group">
                <CardContent className="p-0">
                  {/* Header with Image and Badge */}
                  <div className="relative bg-gradient-to-br from-primary/20 to-primary/5 p-6 pb-8">
                    <div className="absolute top-4 right-4">
                      <Badge className="bg-primary text-primary-foreground font-bold">
                        {testimonial.result}
                      </Badge>
                    </div>
                    <div className="flex items-center gap-4 mb-4">
                      <img 
                        src={testimonial.image} 
                        alt={testimonial.name}
                        className="w-16 h-16 rounded-full border-4 border-background shadow-lg"
                      />
                      <div>
                        <h4 className="font-bold text-lg">{testimonial.name}</h4>
                        <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                      </div>
                    </div>
                    
                    {/* Star Rating */}
                    <div className="flex gap-1 mb-2">
                      {[...Array(5)].map((_, i) => (
                        <Star key={i} className="w-4 h-4 fill-primary text-primary" />
                      ))}
                    </div>
                  </div>

                  {/* Before/After */}
                  <div className="px-6 py-4 bg-muted/30">
                    <div className="grid grid-cols-2 gap-4 text-sm">
                      <div>
                        <div className="text-xs text-muted-foreground font-semibold mb-1">BEFORE</div>
                        <div className="text-destructive font-medium">{testimonial.before}</div>
                      </div>
                      <div>
                        <div className="text-xs text-muted-foreground font-semibold mb-1">AFTER</div>
                        <div className="text-primary font-medium">{testimonial.after}</div>
                      </div>
                    </div>
                  </div>

                  {/* Quote */}
                  <div className="p-6">
                    <Quote className="w-8 h-8 text-primary/20 mb-3" />
                    <p className="text-foreground/90 leading-relaxed mb-4 italic">
                      "{testimonial.quote}"
                    </p>

                    {/* Metrics */}
                    <div className="grid grid-cols-3 gap-3 pt-4 border-t border-border">
                      <div>
                        <div className="text-xs text-muted-foreground mb-1">Revenue</div>
                        <div className="text-sm font-bold text-primary">{testimonial.metrics.revenue}</div>
                      </div>
                      <div>
                        <div className="text-xs text-muted-foreground mb-1">Followers</div>
                        <div className="text-sm font-bold text-primary">{testimonial.metrics.followers}</div>
                      </div>
                      <div>
                        <div className="text-xs text-muted-foreground mb-1">Engagement</div>
                        <div className="text-sm font-bold text-primary">{testimonial.metrics.engagement}</div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Case Studies */}
        <div className="mb-32">
          <div className="text-center mb-16">
            <h3 className="text-4xl font-bold mb-4">
              Case Studies: <span className="text-gradient">The Breakdown</span>
            </h3>
            <p className="text-lg text-muted-foreground">See exactly how operators scaled across different industries</p>
          </div>

          <div className="grid md:grid-cols-3 gap-6">
            {caseStudies.map((study, index) => (
              <Card key={index} className="border-2 border-primary/30 bg-gradient-to-br from-background to-primary/5 hover:shadow-xl transition-all duration-300">
                <CardContent className="p-8">
                  <div className="flex items-center justify-between mb-6">
                    <Badge variant="outline" className="text-sm">{study.industry}</Badge>
                    <Badge className="bg-primary text-primary-foreground">{study.timeline}</Badge>
                  </div>

                  <div className="space-y-4 mb-6">
                    <div className="flex items-center justify-between">
                      <span className="text-sm text-muted-foreground">Followers</span>
                      <div className="text-right">
                        <div className="text-xs line-through text-muted-foreground">{study.startFollowers}</div>
                        <div className="text-lg font-bold text-primary">{study.endFollowers}</div>
                      </div>
                    </div>

                    <div className="h-px bg-border" />

                    <div className="flex items-center justify-between">
                      <span className="text-sm text-muted-foreground">Revenue Generated</span>
                      <div className="text-2xl font-bold text-gradient">{study.revenue}</div>
                    </div>
                  </div>

                  <div className="flex items-start gap-2 p-4 rounded-lg bg-primary/10 border border-primary/20">
                    <CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0 mt-0.5" />
                    <p className="text-sm font-medium">{study.highlight}</p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Video Testimonials */}
        <div className="mb-32">
          <div className="text-center mb-16">
            <h3 className="text-4xl font-bold mb-4">
              Hear It <span className="text-gradient">Directly</span>
            </h3>
            <p className="text-lg text-muted-foreground">Video testimonials from operators who've made it happen</p>
          </div>

          <div className="grid md:grid-cols-3 gap-6">
            {[1, 2, 3].map((i) => (
              <div key={i} className="relative aspect-video rounded-xl overflow-hidden border-2 border-primary/20 bg-gradient-to-br from-primary/20 to-primary/5 group cursor-pointer hover:border-primary/40 transition-all">
                <div className="absolute inset-0 flex items-center justify-center">
                  <div className="w-20 h-20 rounded-full bg-primary/90 flex items-center justify-center group-hover:scale-110 transition-transform">
                    <Play className="w-8 h-8 text-primary-foreground ml-1" fill="currentColor" />
                  </div>
                </div>
                <div className="absolute bottom-0 left-0 right-0 p-4 bg-gradient-to-t from-background to-transparent">
                  <p className="text-sm font-semibold">Success Story #{i}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Trust Badges */}
        <div className="text-center">
          <div className="inline-flex flex-wrap items-center justify-center gap-8 p-8 rounded-2xl bg-card border border-border">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-primary" />
              <span className="text-sm font-medium">200+ Success Stories</span>
            </div>
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-primary" />
              <span className="text-sm font-medium">$12M+ Revenue Generated</span>
            </div>
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-primary" />
              <span className="text-sm font-medium">94% Success Rate</span>
            </div>
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-primary" />
              <span className="text-sm font-medium">40+ Industries</span>
            </div>
          </div>
        </div>

      </div>
    </section>
  );
};

export default ResultsProof;
